excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://franmarin.github.io
title: "Fran's" 
tagline: "code snippets y lo que se tercie"
description: Fran's github website
paginate: 1
