excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://franmarin.github.io
title: "Fran Mar&iacute;n" 
tagline: ""
description: Fran's github website
paginate: 1
baseurl: {{site.baseurl}}{{post.url}}
