excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://franmarin.github.io
title: "Home of Fran Marín" 
tagline: "Code snippets y lo que se tercie"
description: My home on the web
paginate: 1
