excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://franmarin.github.io
title: "My awesome new site" 
tagline: "Educational thoughts"
description: My awesome new site
paginate: 1